// English texts for island (Localization.swift): German text as written in the code -> English.
// Island, menu bar menu and tooltips, Texterkennung, and the messages the Python core sends in
// German (shown translated by IslandCopy.message; the core and its logs stay German).
extension Loc {
    static let island: [String: String] = [
        // done card (IslandCopy)
        "1 Wort": "1 word",
        "%d Wörter": "%d words",
        "Eingefügt": "Pasted",
        "Eingefügt in %@": "Pasted into %@",
        "Überarbeitet": "Edited",
        "Überarbeitet in %@": "Edited in %@",
        "In der Zwischenablage": "On the clipboard",
        "Prompt in der Zwischenablage": "Prompt on the clipboard",
        "Kein Textfeld aktiv. Mit ⌘V überall einfügen.": "No text field active. Paste anywhere with ⌘V.",
        "mit Kontext": "with context",
        "Kopieren": "Copy",
        "Kopiert": "Copied",
        "Text kopieren": "Copy text",
        // processing
        "Dauert länger": "Taking longer",
        "%@ bricht ab": "%@ to cancel",
        // error card without a message
        "Fehler": "Error",

        // screen context on the hovered confirmation (KONTEXT-PLAN.md)
        "Verwendeter Kontext": "Context used",
        "Nur für dieses Diktat genutzt und schon verworfen.": "Used for this dictation only, already discarded.",
        "In %@ ausschalten": "Turn off in %@",
        "Ausgeschaltet": "Turned off",
        "Bildschirmkontext in %@ ausschalten": "Turn off screen context in %@",
        "Kontext aus %@": "Context from %@",
        "Ohne Kontext, %@": "No context, %@",
        "ohne Kontext, %@": "no context, %@",
        //   why it was held back (context.py _LABELS; also in "Befehl: …" and the Kontext-Probe)
        "App ausgenommen": "app excluded",
        "sichere Eingabe aktiv": "secure input on",
        "Passwortfeld": "password field",
        "privates Fenster": "private window",
        "Bedienungshilfen fehlen": "no Accessibility access",
        "kein Textfeld gefunden": "no text field found",
        "kein Textfeld": "no text field",
        "Feld ohne Cursor": "field without cursor",
        "Feld gibt keinen Text her": "field returns no text",
        "App antwortet nicht": "app not responding",
        "Kontext aus": "context off",
        "App gewechselt": "app changed",
        //   rows (main.py _context_card, _run_command)
        "Text am Cursor": "Text at cursor",
        "Ganzes Fenster": "Whole window",
        "Fenster": "Window",
        "Empfänger und Betreff": "Recipients and subject",
        "Namen": "Names",
        "Korrigiert": "Corrected",
        "%@ zu %@": "%@ to %@",
        "Anrede": "Tone",
        "Sie": "formal (Sie)",
        "du": "informal (du)",
        "Markierung": "Selection",
        "%@ Zeichen": "%@ characters",
        "Im Prompt": "In the prompt",
        "%@ aus %@": "%@ from %@",
        "Markierter Text": "Selected text",
        "Fenstertext": "Window text",
        "Text aus dem Eingabefeld": "Input field text",
        "Der Prompt enthält Text vom Bildschirm. Er geht mit, wenn du den Prompt in einen Cloud-Chat einfügst.":
            "The prompt contains text from your screen. It goes along when you paste the prompt into a cloud chat.",

        // messages of the Python core (main.py, transcribe.py, context.py)
        "Mikrofon nicht verfügbar": "Microphone not available",
        "Kein Ton vom Mikrofon, Eingang prüfen": "No sound from the microphone, check the input",
        "Nichts verstanden": "Didn’t catch that",
        "Abgebrochen, nichts eingefügt": "Canceled, nothing pasted",
        "Abgebrochen, Rohtext in der Zwischenablage": "Canceled, raw text on the clipboard",
        "Spracherkennung fehlt, bitte unter Einrichtung laden": "Speech recognition missing, download it in Setup",
        "Spracherkennung hat zu lange gebraucht": "Speech recognition took too long",
        "Fehler bei der Aufbereitung, Rohtext in der Zwischenablage": "Processing failed, raw text on the clipboard",
        "Fehler: %@": "Error: %@",
        "Erst Text markieren, dann halten und sprechen": "Select text first, then hold and speak",
        "Befehl: %@": "Command: %@",
        "Keine Markierung gefunden": "No selection found",
        "Markierung zu lang, höchstens 4.000 Zeichen": "Selection too long, 4,000 characters max",
        "Befehl nicht ausgeführt, Text unverändert": "Command not run, text unchanged",
        "Gelernt: %@": "Learned: %@",
        "Gelernt: %@ wird %@": "Learned: %@ becomes %@",
        "Kontext-Probe: keine App vorne": "Context probe: no app in front",
        "Cursor %@ Zeichen": "cursor %@ characters",
        "Dokument %@": "document %@",
        "Fenster %@": "window %@",

        // Texterkennung (ScreenText)
        "Bereich wählen": "Select an area",
        "Formel wählen": "Select formula",
        "⌥ Formel": "⌥ Formula",
        "Formel erkannt": "Formula recognized",
        "Formelerkennung hat nicht geantwortet": "Formula reader did not answer",
        "Text erkannt": "Text recognized",
        "Tabelle erkannt": "Table recognized",
        "%d Tabellen erkannt": "%d tables recognized",
        "Kein Text gefunden": "No text found",
        "Bildausschnitt nicht lesbar": "Can’t read the selected area",
        "Texterkennung hat nicht geantwortet": "Text recognition didn’t respond",
        "Bildschirmauswahl nicht verfügbar": "Screen selection not available",
        "Bildschirmaufnahme erlauben, dann VoiceBud neu starten": "Allow Screen Recording, then restart VoiceBud",
        "Text im Verlauf, Diktat bleibt in der Ablage": "Text in history, dictation stays on the clipboard",
        "Diktat hatte Vorrang, Text nicht kopiert": "Dictation came first, text not copied",

        // menu bar menu (main.swift) and symbol (MenuBarIcon)
        "Diktat: %@": "Dictation: %@",
        "Prompt: %@": "Prompt: %@",
        "Befehl (halten): %@": "Command (hold): %@",
        "Verlauf & Einstellungen …": "History & Settings…",
        "Kontext-Probe": "Context Probe",
        "Einrichtung …": "Setup…",
        "VoiceBud beenden": "Quit VoiceBud",
        "VoiceBud nimmt auf": "VoiceBud is recording",
        "VoiceBud nimmt auf, Ton stumm": "VoiceBud is recording, sound muted",
        // hotkey names (HotkeyFormat: "⌥ rechts")
        "links": "left",
        "rechts": "right",
    ]
}
